language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t simoncar/docker-react -f Dockerfile.dev .  # f means force to use

script:
  - docker run -e CI=true USERNAME/docker-react npm run test

